{
<<<<<<< HEAD
	"version": 1504551440,
=======
	"version": 1502732279,
>>>>>>> 4acf372b78ac305d279702e4df2059f913c15746
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/scapetinha-sheet0.png",
		"images/spersonagem-sheet0.png",
		"images/spersonagem-sheet1.png",
		"images/spersonagem-sheet2.png",
		"images/sceudaf1-sheet0.png",
		"images/sgramaf1-sheet0.png",
<<<<<<< HEAD
		"images/céumenu-sheet0.png",
		"images/nuvemcreditos-sheet0.png",
		"images/fundomenina-sheet0.png",
		"images/fundomenino-sheet0.png",
		"images/smenino-sheet0.png",
		"images/ceucredinst-sheet0.png",
=======
		"images/céu-sheet0.png",
		"images/nuvemcreditos-sheet0.png",
		"images/nuvemdofundodomenu.png",
		"images/fundomenina-sheet0.png",
		"images/fundomenino-sheet0.png",
		"images/smenino-sheet0.png",
>>>>>>> 4acf372b78ac305d279702e4df2059f913c15746
		"images/cartinha-sheet0.png",
		"images/envelope-sheet0.png",
		"images/caixademens-sheet0.png",
		"images/pébalaozinho-sheet0.png",
		"images/fogo-sheet0.png",
		"images/caixadamensagem-sheet0.png",
		"images/pontadobalao-sheet0.png",
		"images/telinha-sheet0.png",
		"images/anjinhoo-sheet0.png",
		"images/anjinho-sheet0.png",
		"images/sanjinho-sheet0.png",
		"images/sanjoapreensivo-sheet0.png",
		"images/splay-sheet0.png",
		"images/ttitulo.png",
		"images/tinstrucoes.png",
		"images/tcreditos.png",
		"images/scartinha-sheet0.png",
		"images/sfoguinho-sheet0.png",
		"images/nuvemf1-sheet0.png",
		"images/score.png",
		"images/cigarro-sheet0.png",
		"images/cerveja-sheet0.png",
		"images/dinheiro-sheet0.png",
		"images/creator-sheet0.png",
		"images/criadordecoisasmundana-sheet0.png",
		"images/sdestroicoisaserradas-sheet0.png",
<<<<<<< HEAD
=======
		"images/sfescolha.png",
>>>>>>> 4acf372b78ac305d279702e4df2059f913c15746
		"images/vidavazio-sheet0.png",
		"images/vida-sheet0.png",
		"images/coracaofase2-sheet0.png",
		"images/sfderrota.png",
		"images/diabinho-sheet0.png",
		"images/botaodepular-sheet0.png",
		"images/foguinho-sheet0.png",
		"images/foguinho-sheet1.png",
		"images/snuvemdevolta-sheet0.png",
		"images/smouse-sheet0.png",
		"images/stouch-sheet0.png",
		"images/replay-sheet0.png",
		"images/menu-sheet0.png",
		"images/replayv-sheet0.png",
		"images/menuv-sheet0.png",
<<<<<<< HEAD
		"images/botaopulartexto-sheet0.png",
		"images/sprite-sheet0.png",
		"images/criadordediabinho-sheet0.png",
		"images/diabo1-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/dinheiroins-sheet0.png",
		"images/cigarroins-sheet0.png",
		"images/trachejados-sheet0.png",
		"images/luz-sheet0.png",
		"images/sensordir-sheet0.png",
		"images/sensoresq-sheet0.png",
		"images/sprite14-sheet0.png",
		"images/sensordestroidiabo-sheet0.png",
		"images/btpausa-sheet0.png",
		"images/paused-sheet0.png",
		"images/sprite17-sheet0.png",
		"images/x1-sheet0.png",
		"images/muisca1-sheet0.png",
		"images/muisca1-sheet1.png",
		"images/sprite16-sheet0.png",
		"images/sprite16-sheet1.png",
		"images/garfo-sheet0.png",
		"images/tiledbackground.png",
		"images/spritefont8.png",
		"images/pausaf2-sheet0.png",
		"images/x2-sheet0.png",
		"images/musica2-sheet0.png",
		"images/musica2-sheet1.png",
		"images/sprite7-sheet0.png",
=======
		"images/botaodeacelerarv-sheet0.png",
		"images/sprite-sheet0.png",
>>>>>>> 4acf372b78ac305d279702e4df2059f913c15746
		"media/conlisão anjinho.m4a",
		"media/conlisão anjinho.ogg",
		"media/jogo anjinho.m4a",
		"media/jogo anjinho.ogg",
		"media/fogo.m4a",
		"media/fogo.ogg",
		"media/coração.m4a",
		"media/coração.ogg",
		"media/vitoria.m4a",
		"media/vitoria.ogg",
		"media/derrota.m4a",
		"media/derrota.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}